# Generated by Django 3.1.2 on 2021-06-24 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_limit_join', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='四桁の数字を入力してください。', regex='^[0-9]{4}')])),
            ],
        ),
        migrations.CreateModel(
            name='TeamBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=100)),
                ('join_count', models.IntegerField(default=1)),
                ('coach', models.CharField(max_length=20)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_board', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='team_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='api.teamboard'),
        ),
    ]
