# Generated by Django 3.1.2 on 2021-06-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210624_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=60)),
                ('icon_number', models.IntegerField(default=0)),
                ('finished_patern', models.CharField(default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='api.teamboard')),
            ],
        ),
    ]
