# Generated by Django 3.1.2 on 2021-06-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('minitus', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_schedules', to='api.profile')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_schedules', to='api.schedule')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_schedules', to='api.training')),
            ],
        ),
    ]
