# Generated by Django 3.1.2 on 2021-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_finishedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_schedule_count',
            field=models.IntegerField(default=0),
        ),
    ]
